//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoLibraryMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_LEND_RECORD
    {
        public int IDENTITY_FILED { get; set; }
        public int BOOK_ID { get; set; }
        public string KEEPER_ID { get; set; }
        public System.DateTime LEND_DATE { get; set; }
        public Nullable<System.DateTime> CRE_DATE { get; set; }
        public string CRE_USR { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string MOD_USR { get; set; }
    
        public virtual BOOK_DATA BOOK_DATA { get; set; }
    }
}
